### ISSUE TITLE
How To Use Adjust.trackEvent

### ISSUE THREAD

**Issue by ebruchanow** [mano-mykingdom/adjust#2]
Hello, 
could you please explain to me how to track custom events with tokens with your Titanium Module.
I'm having trouble to implements this function into my Titanium App.
It would be very helpful, if you could give a code example.

Kind regards 
EBruchanow

**Comment by manojdcoder** [comment]
Sorry, custom event tracking support is not added yet.

**Comment by ebruchanow** [comment]
Thank you for your reply!
Can you determine a Date when this functionality will be added?

**Comment by manojdcoder** [comment]
I'm not active with Adjust APIs, but I can find some time by this week end. Hopefully by Monday you can have it.

**Comment by manojdcoder** [comment]
83eca5dc6e6a13a3a259f45d29068afd59a9e5e7

**Comment by ebruchanow** [comment]
Thank you very much!
